services:
  unicesil.shibboleth_authenticator:
    class: UniceSIL\ShibbolethBundle\Security\ShibbolethGuardAuthenticator
    arguments: ['%unice_sil_shibboleth%', "@router", "@security.token_storage"]

  unicesil.shibboleth_logout_event:
    class: UniceSIL\ShibbolethBundle\Event\LogoutSuccessHandler
    arguments: ['%unice_sil_shibboleth%', "@router"]